### ISSUE TITLE
NURBS Implementation

### ISSUE THREAD

**Issue by mfcats** [mfcats/SplineLib#17]
# Story
As a user
I want to be able to create NURBS curves and surfaces
so that I can describe more complex geometries.

**Comment by cm314** [comment]
i've implemented evaluation of n-dim nurbs and derivative evaluation for 1-d nurbs (working) and for 2-d nurbs (lastly added test not working) --> find mistake
extend to n-dimensional derivative evaluation? (equation in nurbs book is only for 2d (p.136))
