### ISSUE TITLE
Mocking basis_function tests

### ISSUE THREAD

**Issue by maxspahn** [mfcats/SplineLib#78]
The KnotVector in the basis_function tests should be mocked.

**Comment by maxspahn** [comment]
Knot Vectors in basis function and parameter space has been changed so that they are shared pointers now. I have forgotten to do this in the previous issue concerning the knotvectors.

**Comment by maxspahn** [comment]
This test must equal 0 (requires discussion)
TEST_F(BasisFunctionEx22N72, FirstDerevitveIsEqual2At5_0) {

**Comment by cm314** [comment]
No, 2 should be correct. Look at Figure 2.6 in NURBS book.
